// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4population_model_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4signature_model_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4signature_model_prior_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4signit_model_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4signit_model_infer_populations_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4population_model_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4population_model_mod, 0},
    {"_rcpp_module_boot_stan_fit4signature_model_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4signature_model_mod, 0},
    {"_rcpp_module_boot_stan_fit4signature_model_prior_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4signature_model_prior_mod, 0},
    {"_rcpp_module_boot_stan_fit4signit_model_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4signit_model_mod, 0},
    {"_rcpp_module_boot_stan_fit4signit_model_infer_populations_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4signit_model_infer_populations_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_SignIT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
